version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nefetech_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nefetech_central
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:6-jammy
    container_name: nefetech_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nefetech_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data:
